import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"01 - God With Us",
            artist: "01 - God With Us",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-01%20-%20God%20With%20Us.mp3",
            active: true,
        },
       {
            name:"02 - The Chosen People",
            artist: "02 - The Chosen People",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-02%20-%20The%20Chosen%20People.mp3",
            active: true,
        },
        {
            name:"03 - The Fullness of the Time",
            artist: "03 - The Fullness of the Time",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-03%20-%20The%20Fullness%20of%20the%20Time.mp3",
            active: true,
        },
        {
            name:"04 - Unto You a Saviour",
            artist: "04 - Unto You a Saviour",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-04%20-%20Unto%20You%20a%20Saviour.mp3",
            active: true,
        },
        {
            name:"05 - The Dedication",
            artist: "05 - The Dedication",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-05%20-%20The%20Dedication.mp3",
            active: true,
        },
        {
            name:"06 - We Have Seen His Star",
            artist: "06 - We Have Seen His Star",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-06%20-%20We%20Have%20Seen%20His%20Star.mp3",
            active: true,
        },
        {
            name:"07 - As a Child",
            artist: "07 - As a Child",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-07%20-%20As%20a%20Child.mp3",
            active: true,
        },
        {
            name:"08 - The Passover Visit",
            artist: "08 - The Passover Visit",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-08%20-%20The%20Passover%20Visit.mp3",
            active: true,
        },
        {
            name:"09 - Days of Conflict",
            artist: "09 - Days of Conflict",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-09%20-%20Days%20of%20Conflict.mp3",
            active: true,
        },
        {
            name:"10 - The Voice in the Wilderness	",
            artist: "10 - The Voice in the Wilderness	",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-10%20-%20The%20Voice%20in%20the%20Wilderness.mp3",
            active: true,
        },
        {
            name:"11 - The Baptism",
            artist: "11 - The Baptism",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-11%20-%20The%20Baptism.mp3",
            active: true,
        },
        {
            name:"12 - The Temptation",
            artist: "12 - The Temptation",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-12%20-%20The%20Temptation.mp3",
            active: true,
        },
        {
            name:"13 - The Victory",
            artist: "13 - The Victory",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-13%20-%20The%20Victory.mp3",
            active: true,
        },
        {
            name:"14 - We Have Found the Messias",
            artist: "14 - We Have Found the Messias",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-14%20-%20We%20Have%20Found%20the%20Messias.mp3",
            active: true,
        },
        {
            name:"15 - At the Marriage Feast",
            artist: "15 - At the Marriage Feast",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-15%20-%20At%20the%20Marriage%20Feast.mp3",
            active: true,
        },
        {
            name:"16 - In His Temple",
            artist: "16 - In His Temple",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-16%20-%20In%20His%20Temple.mp3",
            active: true,
        },
        {
            name:"17 - Nicodemus",
            artist: "17 - Nicodemus",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-17%20-%20Nicodemus.mp3",
            active: true,
        },
         {
            name:"18 - He Must Increase",
            artist: "18 - He Must Increase",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-18%20-%20He%20Must%20Increase.mp3",
            active: true,
        },
        {
            name:"19 - At Jacob's Well",
            artist: "19 - At Jacob's Well",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-19%20-%20At%20Jacob%27s%20Well.mp3",
            active: true,
        },
         {
            name:"20 - Except Ye See Signs and Wonders",
            artist: "20 - Except Ye See Signs and Wonders",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-20%20-%20Except%20Ye%20See%20Signs%20and%20Wonders.mp3",
            active: true,
        },
        {
            name:"21 - Bethesda and the Sanhedrin",
            artist: "21 - Bethesda and the Sanhedrin",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-21%20-%20Bethesda%20and%20the%20Sanhedrin.mp3",
            active: true,
        },
        {
            name:"22 - Imprisonment and Death of John",
            artist: "22 - Imprisonment and Death of John",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-22%20-%20Imprisonment%20and%20Death%20of%20John.mp3",
            active: true,
        },
         {
            name:"23 - The Kingdom of God Is at Hand",
            artist: "23 - The Kingdom of God Is at Hand",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-23%20-%20The%20Kingdom%20of%20God%20Is%20at%20Hand.mp3",
            active: true,
        },
        {
            name:"24 - Is Not This the Carpenter's Son",
            artist: "24 - Is Not This the Carpenter's Son",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-24%20-%20Is%20Not%20This%20the%20Carpenter%27s%20Son.mp3",
            active: true,
        },
         {
            name:"25 - The Call by the Sea",
            artist: "25 - The Call by the Sea",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-25%20-%20The%20Call%20by%20the%20Sea.mp3",
            active: true,
        },
        {
            name:"26 - At Capernaum",
            artist: "26 - At Capernaum",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-26%20-%20At%20Capernaum.mp3",
            active: true,
        },
        {
            name:"27 - Thou Canst Make Me Clean",
            artist: "27 - Thou Canst Make Me Clean",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-27%20-%20Thou%20Canst%20Make%20Me%20Clean.mp3",
            active: true,
        },
         {
            name:"28 - Levi-Matthew",
            artist: "28 - Levi-Matthew",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-28%20-%20Levi-Matthew.mp3",
            active: true,
        },
        {
            name:"29 - The Sabbath",
            artist: "29 - The Sabbath",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-29%20-%20The%20Sabbath.mp3",
            active: true,
        },
          {
            name:"30 - He Ordained Twelve",
            artist: "30 - He Ordained Twelve",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-30%20-%20He%20Ordained%20Twelve.mp3",
            active: true,
        },
        {
            name:"31 - The Sermon on the Mount",
            artist: "31 - The Sermon on the Mount",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-31%20-%20The%20Sermon%20on%20the%20Mount.mp3",
            active: true,
        },
         {
            name:"32 - The Centurion",
            artist: "32 - The Centurion",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-32%20-%20The%20Centurion.mp3",
            active: true,
        },
         {
            name:"33 - Who Are My Brethren",
            artist: "33 - Who Are My Brethren",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-33%20-%20Who%20Are%20My%20Brethren.mp3",
            active: true,
        },
         {
            name:"34 - The Invitation",
            artist: "34 - The Invitation",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-34%20-%20The%20Invitation.mp3",
            active: true,
        },
          {
            name:"35 - Peace, Be Still",
            artist: "35 - Peace, Be Still",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-35%20-%20Peace%2C%20Be%20Still.mp3",
            active: true,
        },
        {
            name:"36 - The Touch of Faith",
            artist: "36 - The Touch of Faith",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-36%20-%20The%20Touch%20of%20Faith.mp3",
            active: true,
        },
         {
            name:"37 - The First Evangelists",
            artist: "37 - The First Evangelists",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-37%20-%20The%20First%20Evangelists.mp3",
            active: true,
        },
        {
            name:"38 - Come Rest Awhile",
            artist: "38 - Come Rest Awhile",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-38%20-%20Come%20Rest%20Awhile.mp3",
            active: true,
        },
        {
            name:"39 - Give Ye Them to Eat",
            artist: "39 - Give Ye Them to Eat",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-39%20-%20Give%20Ye%20Them%20to%20Eat.mp3",
            active: true,
        },
         {
            name:"40 - A Night on the Lake",
            artist: "40 - A Night on the Lake",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-40%20-%20A%20Night%20on%20the%20Lake.mp3",
            active: true,
        },
          {
            name:"41 - The Crisis in Galilee",
            artist: "41 - The Crisis in Galilee",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-41%20-%20The%20Crisis%20in%20Galilee.mp3",
            active: true,
        },
         {
            name:"42 - Tradition",
            artist: "42 - Tradition",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-42%20-%20Tradition.mp3",
            active: true,
        },
        {
            name:"43 - Barriers Broken Down",
            artist: "43 - Barriers Broken Down",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-43%20-%20Barriers%20Broken%20Down.mp3",
            active: true,
        },
         {
            name:"44 - The True Sign",
            artist: "44 - The True Sign",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-44%20-%20The%20True%20Sign.mp3",
            active: true,
        },
        {
            name:"45 - The Foreshadowing of the Cross",
            artist: "45 - The Foreshadowing of the Cross",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-45%20-%20The%20Foreshadowing%20of%20the%20Cross.mp3",
            active: true,
        },
         {
            name:"46 - He Was Transfigured",
            artist: "46 - He Was Transfigured",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-46%20-%20He%20Was%20Transfigured.mp3",
            active: true,
        },
        {
            name:"47 - Ministry",
            artist: "47 - Ministry",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-47%20-%20Ministry.mp3",
            active: true,
        },
         {
            name:"48 - Who Is the Greatest",
            artist: "48 - Who Is the Greatest",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-48%20-%20Who%20Is%20the%20Greatest.mp3",
            active: true,
        },
         {
            name:"49 - At the Feast of Tabernacles",
            artist: "49 - At the Feast of Tabernacles",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-49%20-%20At%20the%20Feast%20of%20Tabernacles.mp3",
            active: true,
        },
         {
            name:"50 - Among Snares",
            artist: "50 - Among Snares",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-50%20-%20Among%20Snares.mp3",
            active: true,
        },
        {
            name:"51 - “The Light of Life”",
            artist: "51 - “The Light of Life”",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-51%20-%20%E2%80%9CThe%20Light%20of%20Life%E2%80%9D.mp3",
            active: true,
        },
        {
            name:"52 - The Divine Shepherd",
            artist: "52 - The Divine Shepherd52 - The Divine Shepherd",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-52%20-%20The%20Divine%20Shepherd.mp3",
            active: true,
        },
         {
            name:"53 - The Last Journey From Galilee",
            artist: "53 - The Last Journey From Galilee",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-53%20-%20The%20Last%20Journey%20From%20Galilee.mp3",
            active: true,
        },
        {
            name:"54 - The Good Samaritan",
            artist: "54 - The Good Samaritan",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-54%20-%20The%20Good%20Samaritan.mp3",
            active: true,
        },
        {
            name:"55 - Not With Outward Show",
            artist: "55 - Not With Outward Show",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-55%20-%20Not%20With%20Outward%20Show.mp3",
            active: true,
        },
        {
            name:"56 - Blessing the Children",
            artist: "56 - Blessing the Children",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-56%20-%20Blessing%20the%20Children.mp3",
            active: true,
        },
         {
            name:"57 - “One Thing Thou Lackest”	",
            artist: "57 - “One Thing Thou Lackest”	",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-57%20-%20%E2%80%9COne%20Thing%20Thou%20Lackest%E2%80%9D.mp3",
            active: true,
        },
        {
            name:"58 - “Lazarus, Come Forth”",
            artist: "58 - “Lazarus, Come Forth”",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-58%20-%20%E2%80%9CLazarus%2C%20Come%20Forth%E2%80%9D.mp3",
            active: true,
        },
        {
            name:"59 - Priestly Plottings",
            artist: "59 - Priestly Plottings",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-59%20-%20Priestly%20Plottings.mp3",
            active: true,
        },
         {
            name:"60 - The Law of the New Kingdom",
            artist: "60 - The Law of the New Kingdom",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-60%20-%20The%20Law%20of%20the%20New%20Kingdom.mp3",
            active: true,
        },
        {
            name:"61 - Zacchaeus",
            artist: "61 - Zacchaeus",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-61%20-%20Zacchaeus.mp3",
            active: true,
        },
        {
            name:"62 - The Feast at Simon's House",
            artist: "62 - The Feast at Simon's House",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-62%20-%20The%20Feast%20at%20Simon%27s%20House.mp3",
            active: true,
        },
         {
            name:"63 - “Thy King Cometh”",
            artist: "63 - “Thy King Cometh”",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-63%20-%20%E2%80%9CThy%20King%20Cometh%E2%80%9D.mp3",
            active: true,
        },
        {
            name:"64 - A Doomed People",
            artist: "64 - A Doomed People",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-64%20-%20A%20Doomed%20People.mp3",
            active: true,
        },
         {
            name:"65 - The Temple Cleansed Again",
            artist: "65 - The Temple Cleansed Again",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-65%20-%20The%20Temple%20Cleansed%20Again.mp3",
            active: true,
        },
        {
            name:"66 - Controversy",
            artist: "66 - Controversy",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-66%20-%20Controversy.mp3",
            active: true,
        },
         {
            name:"67 - Woes on the Pharisees",
            artist: "67 - Woes on the Pharisees",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-67%20-%20Woes%20on%20the%20Pharisees.mp3",
            active: true,
        },
        {
            name:"68 - In the Outer Court",
            artist: "68 - In the Outer Court",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-68%20-%20In%20the%20Outer%20Court.mp3",
            active: true,
        },
        {
            name:"69 - On the Mount of Olives",
            artist: "69 - On the Mount of Olives",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-69%20-%20On%20the%20Mount%20of%20Olives.mp3",
            active: true,
        },
         {
            name:"70 - “The Least of These My Brethren”",
            artist: "70 - “The Least of These My Brethren”",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-70%20-%20%E2%80%9CThe%20Least%20of%20These%20My%20Brethren%E2%80%9D.mp3",
            active: true,
        },
        {
            name:"71 - A Servant of Servants",
            artist: "71 - A Servant of Servants",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-71%20-%20A%20Servant%20of%20Servants.mp3",
            active: true,
        },
         {
            name:"72 - “In Remembrance of Me”",
            artist: "72 - “In Remembrance of Me”",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-72%20-%20%E2%80%9CIn%20Remembrance%20of%20Me%E2%80%9D.mp3",
            active: true,
        },
         {
            name:"73 - “Let Not Your Heart Be Troubled”",
            artist: "73 - “Let Not Your Heart Be Troubled”",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-73%20-%20%E2%80%9CLet%20Not%20Your%20Heart%20Be%20Troubled%E2%80%9D.mp3",
            active: true,
        },
        {
            name:"74 - Gethsemane",
            artist: "74 - Gethsemane",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-74%20-%20Gethsemane.mp3",
            active: true,
        },
        {
            name:"75 - Before Annas and the Court of Caiaphas",
            artist: "75 - Before Annas and the Court of Caiaphas",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-75%20-%20Before%20Annas%20and%20the%20Court%20of%20Caiaphas.mp3",
            active: true,
        },
        {
            name:"76 - Judas",
            artist: "76 - Judas",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-76%20-%20Judas.mp3",
            active: true,
        },
         {
            name:"76 - Judas",
            artist: "76 - Judas",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-76%20-%20Judas.mp3",
            active: true,
        },
        {
            name:"77 - In Pilate's Judgment Hall",
            artist: "77 - In Pilate's Judgment Hall",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-77%20-%20In%20Pilate%27s%20Judgment%20Hall.mp3",
            active: true,
        },
        {
            name:"78 - Calvary",
            artist: "78 - Calvary",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-78%20-%20Calvary.mp3",
            active: true,
        },
         {
            name:"79 - “It is Finished”",
            artist: "79 - “It is Finished”",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-79%20-%20%E2%80%9CIt%20is%20Finished%E2%80%9D.mp3",
            active: true,
        },
         {
            name:"80 - In Joseph's Tomb",
            artist: "80 - In Joseph's Tomb",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-79%20-%20%E2%80%9CIt%20is%20Finished%E2%80%9D.mp3",
            active: true,
        },
        {
            name:"81 - “The Lord Is Risen”",
            artist: "81 - “The Lord Is Risen”",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-81%20-%20%E2%80%9CThe%20Lord%20Is%20Risen%E2%80%9D.mp3",
            active: true,
        },
        {
            name:"82 - “Why Weepest Thou”",
            artist: "82 - “Why Weepest Thou”",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-82%20-%20%E2%80%9CWhy%20Weepest%20Thou%E2%80%9D.mp3",
            active: true,
        },
         {
            name:"83 - The Walk to Emmaus",
            artist: "83 - The Walk to Emmaus",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-83%20-%20The%20Walk%20to%20Emmaus.mp3",
            active: true,
        },
         {
            name:"84 - “Peace Be Unto You”",
            artist: "84 - “Peace Be Unto You”",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-84%20-%20%E2%80%9CPeace%20Be%20Unto%20You%E2%80%9D.mp3",
            active: true,
        },
         {
            name:"85 - By the Sea Once More",
            artist: "85 - By the Sea Once More",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-85%20-%20By%20the%20Sea%20Once%20More.mp3",
            active: true,
        },
         {
            name:"86 - Go Teach All Nations",
            artist: "86 - Go Teach All Nations",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-86%20-%20Go%20Teach%20All%20Nations.mp3",
            active: true,
        },
        {
            name:"87 - “To My Father, and Your Father”",
            artist: "87 - “To My Father, and Your Father”",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-87%20-%20%E2%80%9CTo%20My%20Father%2C%20and%20Your%20Father%E2%80%9D.mp3",
            active: true,
        },
       
    ];
}

export default chillHop;


