import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"01 - God With Us",
            artist: "01 - God With Us",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-01%20-%20God%20With%20Us.mp3",
            active: true,
        },
       {
            name:"02 - The Chosen People",
            artist: "02 - The Chosen People",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-02%20-%20The%20Chosen%20People.mp3",
            active: true,
        },
        {
            name:"03 - The Fullness of the Time",
            artist: "03 - The Fullness of the Time",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-03%20-%20The%20Fullness%20of%20the%20Time.mp3",
            active: true,
        },
        {
            name:"04 - Unto You a Saviour",
            artist: "04 - Unto You a Saviour",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-04%20-%20Unto%20You%20a%20Saviour.mp3",
            active: true,
        },
        {
            name:"05 - The Dedication",
            artist: "05 - The Dedication",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-05%20-%20The%20Dedication.mp3",
            active: true,
        },
        {
            name:"06 - We Have Seen His Star",
            artist: "06 - We Have Seen His Star",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-06%20-%20We%20Have%20Seen%20His%20Star.mp3",
            active: true,
        },
        {
            name:"07 - As a Child",
            artist: "07 - As a Child",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-07%20-%20As%20a%20Child.mp3",
            active: true,
        },
        {
            name:"08 - The Passover Visit",
            artist: "08 - The Passover Visit",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-08%20-%20The%20Passover%20Visit.mp3",
            active: true,
        },
        {
            name:"09 - Days of Conflict",
            artist: "09 - Days of Conflict",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-09%20-%20Days%20of%20Conflict.mp3",
            active: true,
        },
        {
            name:"10 - The Voice in the Wilderness	",
            artist: "10 - The Voice in the Wilderness	",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-10%20-%20The%20Voice%20in%20the%20Wilderness.mp3",
            active: true,
        },
        {
            name:"11 - The Baptism",
            artist: "11 - The Baptism",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-11%20-%20The%20Baptism.mp3",
            active: true,
        },
        {
            name:"12 - The Temptation",
            artist: "12 - The Temptation",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-12%20-%20The%20Temptation.mp3",
            active: true,
        },
        {
            name:"13 - The Victory",
            artist: "13 - The Victory",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-13%20-%20The%20Victory.mp3",
            active: true,
        },
        {
            name:"14 - We Have Found the Messias",
            artist: "14 - We Have Found the Messias",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-14%20-%20We%20Have%20Found%20the%20Messias.mp3",
            active: true,
        },
        {
            name:"15 - At the Marriage Feast",
            artist: "15 - At the Marriage Feast",
            cover: "https://ellenwhiteaudio.org/audio/en/da/folder.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ellenwhiteaudio.org/audio/en/da/DA-15%20-%20At%20the%20Marriage%20Feast.mp3",
            active: true,
        },
       
    ];
}

export default chillHop;


